### ISSUE TITLE
как вставить апостроф, если передаю текст содержащий его ? 

### ISSUE THREAD

**Issue by askomarov** [posthtml/gulp-posthtml#28]
<include src="source/html/promo.html" locals='{
        "promoTitle":"all jewellery",
        "promoText":"Discover picks o**f fashion's** finest trends in our jewellery catalog", "className"
      :"catalog__promo" }'></include>

выдает ошибку

### `Environment`

> ℹ️ Please provide information about your current environment.

|OS|node|npm/yarn|package|
|:-:|:--:|:-:|:------:|
|[name][version]|[version]|[version]|[version]|
![image](https://user-images.githubusercontent.com/63908568/129617309-43fdd136-d472-4d0d-843e-43cfa139449b.png)

**Comment by Scrum** [comment]
@askomarov необходимо экранировать.

```html
<include src="source/html/promo.html" locals='{
"promoTitle":"all jewellery",
"promoText":"Discover picks of fashion\'s finest trends in our jewellery catalog", 
"className":"catalog__promo" }'>
```
