### ISSUE TITLE
Example with plugins and options is not working

### ISSUE THREAD

**Issue by mattweb** [posthtml/gulp-posthtml#32]
### `Details`

I failed to get gulp-posthtml running in a project where I had posthtml-include and posthtml-expressions already working with Parcel, Vite and as NPM scripts testcases. But I had to go back to good old gulp.

So I created a test repo with the example gulpfile.js and made commits named with the errors. After switching from import to require, removing options and plugins the file was created in dest.

## `Error (Logs|Stacks)`

- SyntaxError: Cannot use import statement outside a module
- Error: Cannot parse character "<" at 1:1
- tree.parser is not a function

### `Reproduction (Code)`

```bash
$ git clone https://github.com/mattweb/gulp-posthtml-test
```

### `Environment`

|OS|node|npm|package|
|:-:|:--:|:-:|:------:|
|macOS 12.3.1|18.0.0|8.6.0|3.0.5|

Many thanks in advance!

**Comment by Scrum** [comment]
[Here](https://github.com/vitejs/vite/discussions/6659#discussioncomment-3346852) I give an open answer of how you can work with `vitejs`.

Unfortunately `gulp` unclaimed more like `vitejs` and `webpack` and I don't think it's right for us to put a resource here for support, but I will accept any PR if you have.

Feel free to rediscover this one `issue` if I could not answer your questions.
