### ISSUE TITLE
v2.0.0

### ISSUE THREAD

**Issue by michael-ciniawsky** [posthtml/gulp-posthtml#5]
@voischev npm publish please  :)

- [x] Update dotfiles
- [x] Update README.md
- [x] Update posthtml to v0.9.1 (options.parser)
- [x] Add tests
- [x] Add `posthtml-load-config` ( `posthtml.config.js` ) => Autoload Config relative to `dirname(file.path)`

**Comment by voischev** [comment]
done https://www.npmjs.com/package/gulp-posthtml 

and add you to collaborator in npm

write about changes here https://github.com/posthtml/gulp-posthtml/releases/tag/v2.0.0 plz and close issue

**Comment by michael-ciniawsky** [comment]
> and add you to collaborator in npm

Cool thx 👍 , hopefully it's bug free ( it should ;) ), but now I can fix asap if not 😛 

> write about changes here https://github.com/posthtml/gulp-posthtml/releases/tag/v2.0.0 plz and close issue

Yep just a sec :)

**Comment by michael-ciniawsky** [comment]
done [Release Notes](https://github.com/posthtml/gulp-posthtml/releases/tag/v2.0.0)
