### ISSUE TITLE
Problems setting the Options object

### ISSUE THREAD

**Issue by revelt** [posthtml/gulp-posthtml#8]
I'm working with email templates, which have to be in XHTML, so I need closing slashes on single tags.

However, when I set the options object:

    var options = { closingSingleTag: 'slash' }

and use it:

    .pipe(posthtml(plugins, options))

all my closing slashes are **still removed**. I raised and later closed an issue with [PostHTML](https://github.com/posthtml/posthtml/issues/208) regarding this — it's not caused by PostHTML since its [unit tests](https://github.com/posthtml/posthtml/blob/master/test/options.js) prove the settings do work.

I don't see any unit tests covering settings actually working.

Can somebody investigate, is it actually possible to set the `closingSingleTag` in `gulp-posthtml`?

thank you.

**Comment by michael-ciniawsky** [comment]
@revelt This one is my nemesis atm :) Jesus Christ..., there is something buggy in general 'somewhere', could you post your Gulp Config please and log the options `{Object}` out? (Otherwise please provide a test repo so I can do it myself 😛)

**Comment by Scrum** [comment]
@revelt Hi, this [PR](https://github.com/posthtml/posthtml/pull/234) must closed this bug.

**Comment by revelt** [comment]
@GitScrum but it's not merged in yet, isn't it? should I wait until it's merged to 100% confirm?

**Comment by Scrum** [comment]
@revelt yep.

**Comment by revelt** [comment]
OK. If you guys see it's working feel free to close yourselves. I got fed up with this months ago and stopped using PostHTML completely. On the positive side, it made me produce quite few libs on npm.

**Comment by Scrum** [comment]
@revelt try

**Comment by revelt** [comment]
OK, I set it up again, no luck. Same as before, all slashes are still removed from all `img` tags.

![plugins](https://user-images.githubusercontent.com/8344688/33219039-1fb3e928-d138-11e7-9d44-3a6751f6827e.png)

![slashes](https://user-images.githubusercontent.com/8344688/33219063-3adda626-d138-11e7-807b-0f6e614057d0.png)

I'm using `{ closingSingleTag: 'slash' }` as options object. Maybe it's available only in `posthtml-render` where I took it from?

**Comment by revelt** [comment]
By the way I can't fulfil @michael-ciniawsky request and share Gulp settings since it's closed source.

I mean, if anybody's using `gulp-posthtml`, just try flipping your own Gulp plugin settings, to export singleton HTML tags **with** and then **without** the closing slashes. See what happens, see if you can get it working. Because I can't :(

```js
var options = { closingSingleTag: 'slash' }
```

**Comment by Scrum** [comment]
@revelt i work on this, don't worry.

**Comment by Scrum** [comment]
@revelt Hi, i create [demo](https://github.com/inside-demo/gulp-posthtml-demo) and this work for me.
Show me you case.

**Comment by revelt** [comment]
The test is missing plugins, that's where the trouble happens. I'll fork and supplement the demo with a plugin and some CSS via PR. Is that all right?

**Comment by Scrum** [comment]
Yep.

**Comment by revelt** [comment]
Done. Thanks for looking into this. The plugins seem the be "not seeing" the config, `img` is rendered without a slash in both cases after plugin processes the HTML.

**Comment by Scrum** [comment]
Thanks, I will investigate this.

**Comment by Scrum** [comment]
You lost actuar `tree` after call `render`.
I create [PR](https://github.com/codsen/posthtml-email-remove-unused-css/pull/3) which fixed this

**Comment by revelt** [comment]
Aha! My bad. Thank you very much. Closing this.
